// <auto-generated />
using System;
using Luis_Baltodano_AP1_P3.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Luis_Baltodano_AP1_P3.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Luis_Baltodano_AP1_P3.Entidades.Clientes", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroCedula")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Luis_Baltodano_AP1_P3.Entidades.Contratos", b =>
                {
                    b.Property<int>("ContratoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comentarios")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.HasKey("ContratoId");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("Luis_Baltodano_AP1_P3.Entidades.ContratosDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Cantidad")
                        .HasColumnType("REAL");

                    b.Property<int>("ContratoId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Importe")
                        .HasColumnType("REAL");

                    b.Property<float>("MontoTotal")
                        .HasColumnType("REAL");

                    b.Property<int>("serviciosServicioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.HasIndex("serviciosServicioId");

                    b.ToTable("ContratosDetalle");
                });

            modelBuilder.Entity("Luis_Baltodano_AP1_P3.Entidades.Planes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Planes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Internet(5Mbps - 1Mbps) - Cable(120 Canales)"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Internet (100Mbps - 50Mbps) - Cable (300 Canales)"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Internet (5Mbps - 1Mbps)"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "(10Mbps - 5Mbps)"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Internet (100Mbps - 50Mbps)"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Cable (120 Canales)"
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = " Cable (150 Canales)"
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Cable (300 Canales)"
                        });
                });

            modelBuilder.Entity("Luis_Baltodano_AP1_P3.Entidades.Servicios", b =>
                {
                    b.Property<int>("ServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<float>("MontoFacturado")
                        .HasColumnType("REAL");

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Precio")
                        .HasColumnType("REAL");

                    b.HasKey("ServicioId");

                    b.HasIndex("PlanId");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("Luis_Baltodano_AP1_P3.Entidades.ContratosDetalle", b =>
                {
                    b.HasOne("Luis_Baltodano_AP1_P3.Entidades.Contratos", "contratos")
                        .WithMany("ContratosDetalle")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Luis_Baltodano_AP1_P3.Entidades.Servicios", "servicios")
                        .WithMany()
                        .HasForeignKey("serviciosServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("contratos");

                    b.Navigation("servicios");
                });

            modelBuilder.Entity("Luis_Baltodano_AP1_P3.Entidades.Servicios", b =>
                {
                    b.HasOne("Luis_Baltodano_AP1_P3.Entidades.Planes", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Luis_Baltodano_AP1_P3.Entidades.Contratos", b =>
                {
                    b.Navigation("ContratosDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
